apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-rascunho
spec:
  project: default
  source:
    repoURL: https://github.com/EduardoLTech/k8sargocd.git
    targetRevision: main
    path: k8s/argocd-applications/helm/nginx
  destination:
    server: https://192.168.1.10:6443
    namespace: default