apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: primeiro-replica-set
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
        - name: exemplo
          image: nginx:latest