apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-imagem-gcp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api-imagem-gcp=southamerica-east1-docker.pkg.dev/payface-repo/eduardo-argocd/nginx
    argocd-image-updater.argoproj.io/api-imagem-gcp.update-strategy: latest
    argocd-image-updater.argoproj.io/api-imagem-gcp.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/EduardoLTech/k8sargocd.git
    targetRevision: main
    path: k8s/argocd-imagem
  destination:
    server: https://192.168.1.10:6443
    namespace: imagem
  syncPolicy:
    automated:
      prune: true
      selfHeal: true