apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-imagem-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-imagem-gcp
  template:
    metadata:
      labels:
        app: api-imagem-gcp
    spec:
      containers:
        - name: api-imagem-gcp
          image: southamerica-east1-docker.pkg.dev/payface-repo/eduardo-argocd/nginx:1.2.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gcr-credentials