apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-imagem-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-imagem-gcp
  template:
    metadata:
      labels:
        app: api-imagem-gcp
    spec:
      containers:
        - name: api-imagem-gcp
          image: southamerica-east1-docker.pkg.dev/payface-repo/eduardo-argocd/nginx:1.2.0
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gcr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: api-imagem-gcp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30089
  selector:
    app: api-imagem-gcp