apiVersion: v1
kind: Service
metadata:
  name: api-imagem-gcp-service
spec:
  type: NodePort
  selector:
    app: api-imagem-gcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30089