image:
  repository: southamerica-east1-docker.pkg.dev/payface-repo/eduardo-argocd/nginx
  digest: sha256:fd16867a452f3793c20188d18ca8e08c5072e023fd78c6068516a76c19f75151
  pullSecret: gcr-credentials

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30089
