apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 0
  replicas: 2
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
        - name: exemplo
          image: nginx